/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const LibraryRole = IDL.Variant({
  'ResearchScholar' : IDL.Null,
  'Admin' : IDL.Null,
  'GeneralStudent' : IDL.Null,
});
export const Time = IDL.Int;
export const Booking = IDL.Record({
  'startTime' : Time,
  'endTime' : Time,
  'userId' : IDL.Principal,
  'seatId' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'libraryRole' : LibraryRole,
});
export const SeatType = IDL.Variant({
  'reserved' : IDL.Null,
  'general' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignLibraryRole' : IDL.Func([IDL.Principal, LibraryRole], [], []),
  'bookSeat' : IDL.Func([IDL.Nat, Time, Time], [], []),
  'cancelBooking' : IDL.Func([], [], []),
  'getAllBookings' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, Booking))],
      ['query'],
    ),
  'getAllUserProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getAvailableSeats' : IDL.Func(
      [Time, Time],
      [IDL.Vec(IDL.Tuple(IDL.Nat, SeatType))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLibrarySchedule' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getMyBookings' : IDL.Func([], [IDL.Opt(Booking)], ['query']),
  'getSeatConfiguration' : IDL.Func(
      [],
      [
        IDL.Record({
          'reservedSeats' : IDL.Nat,
          'totalSeats' : IDL.Nat,
          'generalSeats' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setLibraryHours' : IDL.Func([IDL.Int, IDL.Int], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const LibraryRole = IDL.Variant({
    'ResearchScholar' : IDL.Null,
    'Admin' : IDL.Null,
    'GeneralStudent' : IDL.Null,
  });
  const Time = IDL.Int;
  const Booking = IDL.Record({
    'startTime' : Time,
    'endTime' : Time,
    'userId' : IDL.Principal,
    'seatId' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'libraryRole' : LibraryRole,
  });
  const SeatType = IDL.Variant({ 'reserved' : IDL.Null, 'general' : IDL.Null });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignLibraryRole' : IDL.Func([IDL.Principal, LibraryRole], [], []),
    'bookSeat' : IDL.Func([IDL.Nat, Time, Time], [], []),
    'cancelBooking' : IDL.Func([], [], []),
    'getAllBookings' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, Booking))],
        ['query'],
      ),
    'getAllUserProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getAvailableSeats' : IDL.Func(
        [Time, Time],
        [IDL.Vec(IDL.Tuple(IDL.Nat, SeatType))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLibrarySchedule' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getMyBookings' : IDL.Func([], [IDL.Opt(Booking)], ['query']),
    'getSeatConfiguration' : IDL.Func(
        [],
        [
          IDL.Record({
            'reservedSeats' : IDL.Nat,
            'totalSeats' : IDL.Nat,
            'generalSeats' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setLibraryHours' : IDL.Func([IDL.Int, IDL.Int], [], []),
  });
};

export const init = ({ IDL }) => { return []; };