/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'startTime' : Time,
  'endTime' : Time,
  'userId' : Principal,
  'seatId' : bigint,
}
export type LibraryRole = { 'ResearchScholar' : null } |
  { 'Admin' : null } |
  { 'GeneralStudent' : null };
export type SeatType = { 'reserved' : null } |
  { 'general' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string, 'libraryRole' : LibraryRole }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignLibraryRole' : ActorMethod<[Principal, LibraryRole], undefined>,
  'bookSeat' : ActorMethod<[bigint, Time, Time], undefined>,
  'cancelBooking' : ActorMethod<[], undefined>,
  'getAllBookings' : ActorMethod<[], Array<[Principal, Booking]>>,
  'getAllUserProfiles' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getAvailableSeats' : ActorMethod<[Time, Time], Array<[bigint, SeatType]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLibrarySchedule' : ActorMethod<[], Array<bigint>>,
  'getMyBookings' : ActorMethod<[], [] | [Booking]>,
  'getSeatConfiguration' : ActorMethod<
    [],
    { 'reservedSeats' : bigint, 'totalSeats' : bigint, 'generalSeats' : bigint }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setLibraryHours' : ActorMethod<[bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];